services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT:-8080}:80"
      - "${SSH_PORT:-8022}:22"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=db
    restart: unless-stopped

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped