services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT:-8080}:80"
      - "${SSH_PORT:-8022}:22"
    volumes:
      - ./src:/var/www/html
      - /tmp
      - /var/log/apache2
      - /var/run
    environment:
      - DB_HOST=db
      - DOMAIN=${DOMAIN:-localhost}
    restart: unless-stopped

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  solution:
    build:
      context: ./solution
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    network_mode: host
    depends_on:
      - web