
CREATE TABLE users (
  id VARCHAR(36) PRIMARY KEY,
  username VARCHAR(36) NOT NULL,
  email VARCHAR(36) NOT NULL UNIQUE,
  password VARCHAR(36) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE points (
    id VARCHAR(36) PRIMARY KEY,
    points INT NOT NULL DEFAULT 0
);